name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: self-hosted
    # runs-on: ubuntu-22.04
    timeout-minutes: 5
    container: rutsky/cpp-test:22
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
