spark.master                local[*]
spark.jars.packages         org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.3,org.elasticsearch:elasticsearch-spark-30_2.12:8.15.3
spark.sql.session.timeZone  UTC
spark.driver.memory         1g
