[Interface]
Address = 10.20.0.2/24
PrivateKey = aHNSYtIuy4H7XUYli8eZrink/RZZSfUEHR3m7q6mmmE=
ListenPort = 51821

[Peer]
PublicKey = xwGKECpEYVhX2nx/Ezare/m8mbfVOjBeTW1wFMef9yQ=
PresharedKey = xyqOa5noRebXRbA7wgR+4Mw15uO94e/6TqS2ozTUmco=
Endpoint = 172.28.0.4:51820
AllowedIPs = 10.20.0.0/24
PersistentKeepalive = 25
