[Interface]
Address = 10.10.0.2/24
PrivateKey = iOW2MtnWbLdbhaOUElw1PR2g6pkNhdIE9uP7w5f6Pls=
ListenPort = 51820

[Peer]
PublicKey = TMPxmxlpT9qX75i+kOUVdDaOhWkduKn7AUY3nn8gfEY=
Endpoint = 172.28.0.3:51820
AllowedIPs = 10.10.0.0/24
PersistentKeepalive = 25
