[Interface]
PrivateKey = cHT3xXSryJkS1FPFVEU2MFXsBWqlDCiLODeJvRYtsG4=
Address = 10.20.0.4/24
ListenPort = 51820

[Peer]
PublicKey = xU/nDbCirmxUrPamO6OXeGl9D/KJ3lrLRmvmwPh9VXU=
PresharedKey = xyqOa5noRebXRbA7wgR+4Mw15uO94e/6TqS2ozTUmco=
AllowedIPs = 10.20.0.2/32
