[Interface]
PrivateKey = 4OeUh0ONgupt/Fwhw2/YIPq+uViUEbzOTL9wokg0LFY=
Address = 10.10.0.3/24
ListenPort = 51820

[Peer]
PublicKey = nvIYhzSsSlocyQjWdw/Ehku6fHFIDxbhLH1B0H9OV3Y=
AllowedIPs = 10.10.0.2/32
