CXX=g++
CXXFLAGS=$(CFLAGS) -std=c++20

smoke_task_1_strcmp:
	$(CXX) $(CXXFLAGS) \
		./src/task_1/strcmp.cpp \
		./src/task_1/test_strcmp.cpp \
		-o smoke_task_1_strcmp

smoke_task_1_nearest_same:
	@$(CXX) $(CXXFLAGS) \
		./src/task_1/find_nearest_same.cpp \
		./src/task_1/test_find_nearest_same.cpp \
		-o smoke_task_1_nearest_same

smoke_task_2:
	@$(CXX) $(CXXFLAGS) \
		./src/task_2/array_utils.cpp \
		./src/task_2/test.cpp \
		-o smoke_task_2

smoke_task_3:
	@$(CXX) $(CXXFLAGS) \
		./src/task_3/ladder_combination.cpp \
		./src/task_3/test.cpp \
		-o smoke_task_3
