from ipaddress import IPv4Interface

from test_infra.containerlab.network_objects import Interface, Host, Cluster


CLUSTER = Cluster(
    hosts=[
        Host(
            name="PC1",
            interfaces=[
                Interface(
                    name="eth1",
                    ip=IPv4Interface("172.16.11.1/30"),
                ),
            ],
        ),
        Host(
            name="PC2",
            interfaces=[
                Interface(
                    name="eth1",
                    ip=IPv4Interface("172.16.22.1/30"),
                ),
            ],
        ),
        Host(
            name="leaf1",
            interfaces=[
                Interface(
                    name="eth5",
                    ip=IPv4Interface("172.16.114.2/30"),
                ),
                Interface(
                    name="eth4",
                    ip=IPv4Interface("172.16.113.2/30"),
                ),
                Interface(
                    name="eth3",
                    ip=IPv4Interface("172.16.11.2/30"),
                ),
                Interface(
                    name="eth2",
                    ip=IPv4Interface("172.16.111.2/30"),
                ),
                Interface(
                    name="eth1",
                    ip=IPv4Interface("172.16.112.2/30"),
                ),
            ],
        ),
        Host(
            name="leaf2",
            interfaces=[
                Interface(
                    name="eth5",
                    ip=IPv4Interface("172.16.224.2/30"),
                ),
                Interface(
                    name="eth4",
                    ip=IPv4Interface("172.16.223.2/30"),
                ),
                Interface(
                    name="eth3",
                    ip=IPv4Interface("172.16.22.2/30"),
                ),
                Interface(
                    name="eth2",
                    ip=IPv4Interface("172.16.222.2/30"),
                ),
                Interface(
                    name="eth1",
                    ip=IPv4Interface("172.16.221.2/30"),
                ),
            ],
        ),
        Host(
            name="spine1",
            interfaces=[
                Interface(
                    name="eth2",
                    ip=IPv4Interface("172.16.111.1/30"),
                ),
                Interface(
                    name="eth1",
                    ip=IPv4Interface("172.16.221.1/30"),
                ),
            ],
        ),
        Host(
            name="spine2",
            interfaces=[
                Interface(
                    name="eth2",
                    ip=IPv4Interface("172.16.222.1/30"),
                ),
                Interface(
                    name="eth1",
                    ip=IPv4Interface("172.16.112.1/30"),
                ),
            ],
        ),
        Host(
            name="spine3",
            interfaces=[
                Interface(
                    name="eth2",
                    ip=IPv4Interface("172.16.113.1/30"),
                ),
                Interface(
                    name="eth1",
                    ip=IPv4Interface("172.16.223.1/30"),
                ),
            ],
        ),
        Host(
            name="spine4",
            interfaces=[
                Interface(
                    name="eth2",
                    ip=IPv4Interface("172.16.224.1/30"),
                ),
                Interface(
                    name="eth1",
                    ip=IPv4Interface("172.16.114.1/30"),
                ),
            ],
        ),
    ]
)
