[tool.poetry]
name = "hw2"
version = "0.1.0"
description = ""
authors = ["fadyat <fadyat@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
tex-gen-v2 = "^0.1.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.7.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
