tex:
	@mkdir -p out
	@cd src && \
        pdflatex -file-line-error \
        -interaction=nonstopmode \
        -synctex=1 \
        -output-format=pdf \
        -output-directory=../out \
        ./algo_template.tex
