CXX=g++
CXXFLAGS=-Wall -Werror -std=c++20

smoke_task_1:
	@$(CXX) $(CXXFLAGS) ./src/task_1/test.cpp ./src/task_1/hello.cpp -o smoke_task_1

smoke_task_2:
	@$(CXX) $(CXXFLAGS) ./src/task_2/test.cpp ./src/task_2/fizzbuzz.cpp -o smoke_task_2

smoke_task_3:
	@$(CXX) $(CXXFLAGS) ./src/task_3/test.cpp ./src/task_3/compute_fib.cpp -o smoke_task_3

clear:
	@rm smoke_task_*
